#print("Hello World!")
##print("Hell Again")
#print("I like typing this.")
#print("This is fun")
#print('yay! Printing.')
#print("I'd much rather you 'not'.")
#print('I "said" do not touch this.')
print("another line")
print("really?")
